export const GET_ALL_GENRES_PENDING = 'GET_ALL_GENRES';
export const GET_ALL_GENRES_SUCCESS = 'GET_ALL_GENRES_SUCCESS';
export const GET_ALL_GENRES_FAILURE = 'GET_ALL_GENRES_FAILURE';
export const GET_GENRE_BY_ID_PENDING = 'GET_GENRE_BY_ID';
export const GET_GENRE_BY_ID_SUCCESS = 'GET_GENRE_BY_ID_SUCCESS';
export const GET_GENRE_BY_ID_FAILURE = 'GET_GENRE_BY_ID_FAILURE';